          path: |
            ${{ github.workspace }}/${{ steps.resolve.outputs.soc }}/build.log
            ${{ github.workspace }}/${{ steps.resolve.outputs.soc }}/ksu-driver-build.log
            ${{ github.workspace }}/${{ steps.resolve.outputs.soc }}/kpm-patch.log
            ${{ github.workspace }}/${{ steps.resolve.outputs.soc }}/vmlinux-symbols.txt
            ${{ github.workspace }}/${{ steps.resolve.outputs.soc }}/susfs-source-proof.txt
            ${{ github.workspace }}/${{ steps.resolve.outputs.soc }}/susfs-hook-proof.txt
            ${{ github.workspace }}/${{ steps.resolve.outputs.soc }}/susfs-proof.txt
            ${{ github.workspace }}/${{ steps.resolve.outputs.soc }}/out/.config
            ${{ github.workspace }}/${{ steps.resolve.outputs.soc }}/out/arch/arm64/boot/Image
            ${{ github.workspace }}/${{ steps.resolve.outputs.soc }}/out/arch/arm64/boot/Image.unpatched
            ${{ github.workspace }}/${{ env.ZIP_NAME }}.zip
